// Code generated by go generate; DO NOT EDIT.
package entry

type ID string

const NoID ID = ""

func (id ID) String() string {
	return string(id)
}

func (id ID) Valid() bool {
	return id != NoID
}

func ParseID(s string) ID {
	return ID(s)
}
