// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/finebiscuit/api/services/forex/currency"
	"github.com/shopspring/decimal"
)

type BalancePayload struct {
	Balance *Balance `json:"balance"`
}

type BalanceValue struct {
	Currency currency.Currency `json:"currency"`
	Value    decimal.Decimal   `json:"value"`
	ValidAt  time.Time         `json:"validAt"`
	Year     int               `json:"year"`
	Month    int               `json:"month"`
}

type CreateBalanceInput struct {
	Currency                    currency.Currency `json:"currency"`
	Kind                        string            `json:"kind"`
	Value                       decimal.Decimal   `json:"value"`
	DisplayName                 *string           `json:"displayName"`
	OfficialName                *string           `json:"officialName"`
	Institution                 *string           `json:"institution"`
	EstimatedMonthlyGrowthRate  *decimal.Decimal  `json:"estimatedMonthlyGrowthRate"`
	EstimatedMonthlyValueChange *decimal.Decimal  `json:"estimatedMonthlyValueChange"`
}

type PreferencesPayload struct {
	Preferences *Preferences `json:"preferences"`
}

type UpdateBalanceInfoInput struct {
	BalanceID                   string           `json:"balanceId"`
	DisplayName                 *string          `json:"displayName"`
	OfficialName                *string          `json:"officialName"`
	Institution                 *string          `json:"institution"`
	EstimatedMonthlyGrowthRate  *decimal.Decimal `json:"estimatedMonthlyGrowthRate"`
	EstimatedMonthlyValueChange *decimal.Decimal `json:"estimatedMonthlyValueChange"`
}

type UpdateBalanceValueInput struct {
	BalanceID string `json:"balanceId"`
	Value     string `json:"value"`
}

type UpdatePreferencesParams struct {
	DefaultCurrency     *currency.Currency  `json:"defaultCurrency"`
	SupportedCurrencies []currency.Currency `json:"supportedCurrencies"`
}

type Version struct {
	Canonical string `json:"canonical"`
}
