// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BalancePayload struct {
	Balance *Balance `json:"balance"`
}

type CreateBalanceInput struct {
	Currency     string  `json:"currency"`
	Kind         string  `json:"kind"`
	Value        string  `json:"value"`
	DisplayName  *string `json:"displayName"`
	OfficialName *string `json:"officialName"`
	Institution  *string `json:"institution"`
}

type UpdateBalanceInfoInput struct {
	BalanceID    string  `json:"balanceId"`
	DisplayName  *string `json:"displayName"`
	OfficialName *string `json:"officialName"`
	Institution  *string `json:"institution"`
}

type UpdateBalanceValueInput struct {
	BalanceID string `json:"balanceId"`
	Value     string `json:"value"`
}
